Fix external dependency on highlight constants
SublimeLinter v4.0.0 introduced a breaking change during the refactoring
of the `highlight` module (exception below) which was changed to `const`.
This change also affected other linters like "SublimeLinter-annotations"
and so we started a campaign to fix all the dependent packages here [1].

[1] https://github.com/SublimeLinter/SublimeLinter/issues/915

```
reloading plugin SublimeLinter-contrib-golint.linter
Traceback (most recent call last):
  File "/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Packages/SublimeLinter-contrib-golint/linter.py", line 13, in <module>
    from SublimeLinter.lint import Linter, util, highlight, persist
ImportError: cannot import name highlight
```